### ISSUE TITLE
pip install fails on Arch

### ISSUE THREAD

**Issue by drewhoener** [rpi-ws281x/rpi-ws281x-python#12]
Trying to install via pip and I keep getting an unexpected error. Didn't see anything mentioning it in a previous arch issue post so figured I'd throw it here. Any thoughts?
![screenshot-2018-09-01-10 06 21](https://user-images.githubusercontent.com/6218989/44946700-1eb7d600-adcf-11e8-9315-f1fcf6dc0817.png)

EDIT: Should probably clarify, my goal is to write my code off of the pi using the library on my main workstation which is faster and then move it to the pi when I'm done. Is this achievable?

**Comment by Gadgetoid** [comment]
Closed as stale.
