### ISSUE TITLE
RuntimeError when using within Docker container

### ISSUE THREAD

**Issue by charliesneath** [rpi-ws281x/rpi-ws281x-python#14]
When running my program within a Docker container, I get the following error, which I believe is related to `rpi_ws281xs`'s ability to interact with the hardware from the Docker container:

```
RuntimeError: ws2811_init failed with code -9 (Failed to create mailbox device)
```

Is there a way to make this library work within a Docker container?

Also reported at https://github.com/jgarff/rpi_ws281x/issues/351.

**Comment by charliesneath** [comment]
@Gadgetoid Any ideas on this error? Is there additional information I can provide to help debug/evaluate?

**Comment by sylvek** [comment]
@charliesneath Do you run your docker with user 0, group 0 and privileged option?

**Comment by charliesneath** [comment]
@sylvek I wasn't setting this explicitly, but I will look into doing so. Do you have any examples?

**Comment by sylvek** [comment]
`docker run --privileged …` should work.

based on docker is running with root account

**Comment by charliesneath** [comment]
@sylvek That did the trick, thank you.

**Comment by janblumenkamp** [comment]
Is there any way to get this to work without the --privileged mode? What devices should be mapped to the docker container?

**Comment by Gadgetoid** [comment]
> Is there any way to get this to work without the --privileged mode? What devices should be mapped to the docker container?

This would be better asked on the repo for the underlying library, since the Python bindings don't affect its limitations - https://github.com/jgarff/rpi_ws281x

However, I suspect the answer is no. But you could paint what I know about Docker on the head of a pin with a firehose.
