### ISSUE TITLE
WS281x on raspberry PI 4 hardware revision

### ISSUE THREAD

**Issue by e-fadil** [rpi-ws281x/rpi-ws281x-python#18]
Hi, I'm trying to use the WS281x library on raspberry pi 4 but get the error below, works fine on rasberry pi 3.

JDK Server VM warning: You have loaded library /tmp/libws281xj10313733273385733761.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c ', or link it with '-z noexecstack'.
Error loading library from classpath, trying from system library path
Loaded library 'ws281xj' from system library path
ws2811_init failed: Hardware revision is not supported
Exception in thread "main" java.lang.RuntimeException: Error initialising the WS281x strip
at com.diozero.ws281xj.WS281x.(WS281x.java:165)
at com.diozero.ws281xj.WS281x.(WS281x.java:132)

A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x9351e664, pid=1036, tid=1058

JRE version: OpenJDK Runtime Environment (11.0.3+7) (build 11.0.3+7-post-Raspbian-5)
Java VM: OpenJDK Server VM (11.0.3+7-post-Raspbian-5, mixed mode, g1 gc, linux-)
Problematic frame:
C [libws281xj.so+0x2664] ws2811_fini+0xc

No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

An error report file with more information is saved as:
/home/pi/Desktop/hs_err_pid1036.log

If you would like to submit a bug report, please visit:
Unknown
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

**Comment by Gadgetoid** [comment]
From what I can tell from your output, you're not using Python or the Python bindings.

Are you sure you're using the `rpi-ws281x-python` Python bindings and not https://github.com/jgarff/rpi_ws281x/ directly?
