### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by spanout** [rpi-ws281x/rpi-ws281x-python#20]
Hi

Love the library but getting segmentation fault on PiZero when running your sample in a function. It happens when running channel = ws.ws2811_channel_get(leds, LED_CHANNEL). The sample python script also suffered the same but periodically, but this happens all the time

`
leds = ws.new_ws2811_t()
def initLEDs():

    # Initialize all channels to off
    for channum in range(2):
        channel = ws.ws2811_channel_get(leds, channum)
        ws.ws2811_channel_t_count_set(channel, 0)
        ws.ws2811_channel_t_gpionum_set(channel, 0)
        ws.ws2811_channel_t_invert_set(channel, 0)
        ws.ws2811_channel_t_brightness_set(channel, 0)

    channel = ws.ws2811_channel_get(leds, LED_CHANNEL)

    ws.ws2811_channel_t_count_set(channel, LED_COUNT)
    ws.ws2811_channel_t_gpionum_set(channel, LED_GPIO)
    ws.ws2811_channel_t_invert_set(channel, LED_INVERT)
    ws.ws2811_channel_t_brightness_set(channel, LED_BRIGHTNESS)

    ws.ws2811_t_freq_set(leds, LED_FREQ_HZ)
    ws.ws2811_t_dmanum_set(leds, LED_DMA_NUM)

    # Initialize library with LED configuration.
    resp = ws.ws2811_init(leds)
    if resp != ws.WS2811_SUCCESS:
            message = ws.ws2811_get_return_t_str(resp)
            raise RuntimeError('ws2811_init failed with code {0} ({1})'.format(resp, message))
        
    
def transition(r,g,b):

    

   
    try:
            channel = ws.ws2811_channel_get(leds, LED_CHANNEL)
            for i in range(LED_COUNT):
                    #print("setting rgb to " + int(convertrgb(level_r,level_g, level_b),0))
                    ws.ws2811_led_set(channel, i, int(convertrgb(level_r,level_g, level_b),0))
                
            resp = ws.ws2811_render(leds)
            if resp != ws.WS2811_SUCCESS:
                    message = ws.ws2811_get_return_t_str(resp)
                    raise RuntimeError('ws2811_render failed with code {0} ({1})'.format(resp, message))

    finally:

            ws.ws2811_fini(leds)

            ws.delete_ws2811_t(leds)
`

**Comment by Gadgetoid** [comment]
Closed as stale.
