### ISSUE TITLE
Raspberry Pi 4 Rev 1.2

### ISSUE THREAD

**Issue by TheChuckWhite** [rpi-ws281x/rpi-ws281x-python#30]
I am copy pasting my issue from jgarff's repo here since I dont know which is the right repo to ask for updates.

Hi, just got a new Raspberry Pi 4 and tried to run my old code when i get this error message:
`RuntimeError: ws2811_init failed with code -3 (Hardware revision is not supported)
`

Some other people had this problem with older models before and so I checked my Revision with `cat /proc/cpuinfo` and is says 
`Revision	: c03112`
`Model: Raspberry Pi 4 Model B Rev 1.2`

and compared it with the revision in rpihw.c and there was the problem:
`//Raspberry Pi 4`
`.hwver = 0xC03111,`

After a quick change I thought I am done, but now I'm just too stupid to install the lib into the right directory because the -d flag for `setup.py install` is not working (the error message says to specify the lib directory with -d because the default one seems to be wrong for me).

I've only used pip to install libs, so I really don't know how to do that stuff. Hope it gets updated soon.

**Comment by pilotak** [comment]
i tested v4.2.3 on Pi4 rev 1.2 4GB RAM on pin 12 and it works like a charm. In order to install you need `git clone --recurse-submodules`
