### ISSUE TITLE
Pulse brightness up and down?

### ISSUE THREAD

**Issue by emdeex** [rpi-ws281x/rpi-ws281x-python#39]
I see the overall strip brightness is set as one-time variable.

`LED_BRIGHTNESS = 255  # Set to 0 for darkest and 255 for brightest`

Can I use a function like 'rainbowCycle' and have it run through brightness from 0 to 255 over an interval and reverse and repeat?  Possible?

**Comment by jwnicholas99** [comment]
Yep I'm pretty sure you can - in `library/rpi_ws281x/rpi_ws281x.py`, there is a `PixelStrip` class method called `setBrightness()` that will allow you to modify the brightness of the LED strip.
