### ISSUE TITLE
Trying to run code from this module in conjunction with remo.tv Controller results in memory leak.

### ISSUE THREAD

**Issue by JohnMackYouTube05** [rpi-ws281x/rpi-ws281x-python#43]
So I've used this module to control the LEDs on my Kano light ring. The 'strandtest.py' file works FLAWLESSLY! But every time I run some of the exact same code from the test file in conjunction with my remo.tv controller, it spits out this error on startup: `swig/python detected a memory leak of type 'ws2811_t *', no destructor found.`
PLEASE HELP! I want to fix this and get the LEDs working!

I'm running this off a Raspberry Pi 3B+, if that helps.
Thanks,
John

**Comment by Gadgetoid** [comment]
Closed as stale.
