### ISSUE TITLE
permission denied for /dev/mem

### ISSUE THREAD

**Issue by denalena** [rpi-ws281x/rpi-ws281x-python#45]
Hi there, thank you for this great piece of software.

Is there a way to use this lib as the normal pi user?I have to use sudo, otherwise I get:
`Can't open /dev/mem: Permission denied`

edit: from what I've read so far, I think now there's /dev/gpiomem to get around this problem. Is there a way to use that instead of /dev/mem?

edit2: this seems to be related/the same issue as the following: https://github.com/jgarff/rpi_ws281x/issues/133

**Comment by train-do** [comment]
Are you closing this case because you found a solution or something else? If you found a solution, could you share it? I've run "sudo chmod 660 /dev/mem", "sudo usermod -a -G kmem pi"

**Comment by shemminger** [comment]
The DPDK project does not use github for problem reports or pull requests.
Read contributing section in doc for reference to mailing list, and bugzilla.
