### ISSUE TITLE
Add Numpy support

### ISSUE THREAD

**Issue by stsdc** [rpi-ws281x/rpi-ws281x-python#60]
Will numpy speed up an execution of `setPixelColorRGB()`?

I'm currently creating numpy array based on the audio signal, so latency is important. Unfortunately it is impossible to pass numpy array to a `setPixelColorRGB()` since it is not in the standard Python `int` type. I'm wondering if it is a bottleneck or is a Python as a whole?

**Comment by cp2004** [comment]
> Will numpy speed up an execution of setPixelColorRGB()?

Probably not, unless it can do some magic to make it much faster. The underlying code for this lib is written in C.   Adding huge dependencies such as Numpy would complicate installation.

There's very little Python code around, it mostly goes straight to the C side. Could you share some data on what you are seeing as a bottleneck? I've been able to push the LEDs quite fast in some tests.

**Comment by Gadgetoid** [comment]
Closed as stale.

**Comment by shadoxxhd** [comment]
In a replication of the python structure (PixelStrip.setPixelColor -> PixelStrip.__setitem__ -> ws2811_led_set), for 1000 LEDs updating the whole strip to a new color takes 1ms; 5000 LEDs would take 5.6ms.
With numpy, it would take the python side approximately 4us (10us for 5000 LEDs) to pass the data.

This means that while it's not a problematic bottleneck in most situations (with 1000 LEDs and 800kbit/s, you could only reach 25 fps ie. 40ms per frame), implementing a numpy interface should still slightly improve performance in some situations.

Besides that, a numpy interface would also allow **much** more convenient access to the LED data - eg. setting a segment to a new color would simplify from `for i in range(a,b): strip.setPixelColor(i, col)` to `strip[a:b]=col`.
So even if it wasn't possible to adjust the C wrapper to take advantage of numpy performance, implementing a numpy interface would make usage of the library much more convenient.
