### ISSUE TITLE
ws2811_init failed with code -5 (mmap() failed)

### ISSUE THREAD

**Issue by bhattpriti** [rpi-ws281x/rpi-ws281x-python#61]
Hello,

I am using rpi_ws2812 and just copy past rpi_ws281x-python program to my python program but it is giving me error 
ws2811_init failed with code -5 (mmap() failed).
if I commect out 
LED_PIN        = 10      # GPIO pin connected to the pixels (10 uses SPI /dev/spidev0.0).
LED light stays white and not changing colors.
Please Help.

**Comment by lbt** [comment]
If you are not using the SPI interface you need to run as root.

**Comment by bhattpriti** [comment]
Thank you David

Thanks and Regards,
Priti Bhatt
________________________________

**Comment by bhattpriti** [comment]
> If you are not using the SPI interface you need to run as root.
