### ISSUE TITLE
Update ws281x and release new version

### ISSUE THREAD

**Issue by timonsku** [rpi-ws281x/rpi-ws281x-python#69]
Hi @Gadgetoid, connecting to https://github.com/jgarff/rpi_ws281x/commit/7624b7828829497bfbbd6b13e7afd1f05593f7c6 could you also bump the commit in here and release a new version on pypi? :)
That would help me a lot with my CM4 boards.

**Comment by Gadgetoid** [comment]
Should be updated as v4.3.0.
