### ISSUE TITLE
Red and Green backwards?

### ISSUE THREAD

**Issue by vicricker** [rpi-ws281x/rpi-ws281x-python#7]
Red and Green seem to be backwards.
strandtest.py has this:
            colorWipe(strip, Color(255, 0, 0))  # Red wipe
            colorWipe(strip, Color(0, 255, 0))  # Blue wipe
            colorWipe(strip, Color(0, 0, 255))  # Green wipe
The comments are wrong in any case.  I would expect to see Red, then, Green, then Blue, but in reality, I get Green, Red, Blue.

Using the original rpi-ws281x code, the colors are correct.

**Comment by MartorSkull** [comment]
You probably need to change the strip_type when creating the strip object. Like this:

```python
import time
from rpi_ws281x import PixelStrip, Color, ws  # add this ws to the import list
import argparse

...

LED_BRIGHTNESS = 255
LED_INVERT = False
LED_CHANNEL = 0
STRIP_TYPE = rpi_ws281x.ws.rpi_ws281x.ws.WS2811_STRIP_RGB   # Add this line

...

    strip = PixelStrip(LED_COUNT, LED_PIN, LED_FREQ_HZ, LED_DMA, LED_INVERT, LED_BRIGHTNESS, LED_CHANNEL, STRIP_TYPE) # add the STRIP_TYPE argument

...
```

I chose the rgb type because of your post. I may have gotten it wrong though. You still may need to change the type, the types are:

```python
WS2811_STRIP_RGB
WS2811_STRIP_RBG
WS2811_STRIP_GRB # This one is the default
WS2811_STRIP_GBR
WS2811_STRIP_BRG
WS2811_STRIP_BGR
```
