### ISSUE TITLE
after update raspi version to 5.10.17, rpi_ws281x cannot control ledstrip

### ISSUE THREAD

**Issue by dfybc** [rpi-ws281x/rpi-ws281x-python#71]
after update raspi version to 5.10.17, rpi_ws281x cannot control ledstrip
any one know a solution?

**Comment by lbt** [comment]
Could it be linked to this https://github.com/jgarff/rpi_ws281x/issues/447

**Comment by dfybc** [comment]
> Could it be linked to this [jgarff/rpi_ws281x#447](https://github.com/jgarff/rpi_ws281x/issues/447)

I think it is not  a same issue.

my raspios version is 2021-05-07 buster, hardware is raspi 3B, 
i control ledstrip with PWM on pin18, 
but no led will light. 
any body know why?

ps: I test on lastest bullseye version, it does not work  either.
but I test the same SD card on Pi 4B and zero 2 W， the ledstrip worked。

**Comment by x3l51** [comment]
Can you share the wiring and settings on the rPi you did? I've run into the same problem and couldn't solve it even by changing rPi versions.
